DatabaseObject Class Reference
An object representing a domino database object
Public Member Functions
DatabaseObject (string filePath, string server, SessionObject session)
Database constructor method
DatabaseObject (SessionObject session, string replicationID, string server)
Database constructor method
bool Initialize ()
Initializes the DatabaseObject by validating the input and triggering the database request
DocumentObject GetDocument (string unid)
Retrieve a document from this database by universalID
DocumentObject GetDocumentAndFiles (string unid)
Retrieve a document from this database by universalID This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
DocumentObject GetDocumentByKey (string searchField, string searchValue)
Retrieve a document from this database by searching for a specific value in the provided field.
DocumentObject GetDocumentAndFilesByKey (string searchField, string searchValue)
Retrieve a document from this database by searching for a specific value in the provided field. This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
DocumentObject GetDocumentByFormula (string formula)
Retrieve a document from this database by searching using the provided formula.
DocumentObject GetDocumentAndFilesByFormula (string formula)
Retrieve a document from this database by searching using the provided formula. This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetAllDocuments ()
Retrieve all documents from the database
bool GetAllDocumentsAndFiles ()
Retrieve all documents from the database This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetAllDocumentsByFormula (string formula)
Retrieve all documents from this database that correspond to the provided formula
bool GetAllDocumentsAndFilesByFormula (string formula)
Retrieve all documents from this database that correspond to the provided formula This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetAllDocumentsByUnids (string unids)
Retrieve all documents from this database by universalIDs
bool GetAllDocumentsAndFilesByUnids (string unids)
Retrieve all documents from this database by universalIDs This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetAllDocumentsByUnids (IList listUnids)
Retrieve all documents from this database by universalIDs
bool GetAllDocumentsAndFilesByUnids (IList listUnids)
Retrieve all documents from this database by universalIDs This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetAllDocumentsByKey (string searchField, string searchValue)
Retrieve all documents from this database by searching for a specific value in the provided field
bool GetAllDocumentsAndFilesByKey (string searchField, string searchValue)
Retrieve all documents from this database by searching for a specific value in the provided field This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool LoadDocumentFields (string listFields)
Retrieve fields for all documents in the property 'Documents'
bool LoadDocumentFields (IList listFields)
Retrieve fields for all documents in the property 'Documents'
bool LoadDocumentFiles ()
Retrieve file objects for all documents in the property 'Documents'
Properties
SessionObject Session [get]
Reference to the session object that retrieve this database object
bool IsInitialized [get]
Indicates is the DatabaseObject has been initialized
string FilePath [get, set]
Database FilePath
string ReplicationID [get, set]
Database ReplicationID
string ServerName [get, set]
Database ServerName
string Title [get, set]
Database Title
string Template [get, set]
Database Template name
string Size [get, set]
Database size (bytes, Kb, Mb, Gb, Tb)
string Url [get, set]
Database URL
Dictionary< string, DocumentObject > Documents [get, set]
Collection of retrieved DocumentObjects stored in a dictionary with key universalID of the document
Detailed Description
An object representing a domino database object
The following is an example of the usage of a DatabaseObject:
DatabaseObject dbObj = new DatabaseObject(filePath, dominoServerName,
      sessionObject); // by FilePath
// DatabaseObject dbObj = new DatabaseObject(sessionObject, replicationID, dominoServerName); // by
       ReplicationID
if(dbObj!=null &amp;&amp; dbObj.Initialize()){
     // your code here...
}
Definition at line 18 of file DatabaseObject.cs.
Constructor & Destructor Documentation
DatabaseObject() [1/2]
DatabaseObject.DatabaseObject (string filePath, string server, SessionObject session)
Database constructor method
Parameters
filePath
server
session
Definition at line 170 of file DatabaseObject.cs.
                                                                                  {
        _Session = session;
        _FilePath = filePath;
        _ServerName = server;
    }
DatabaseObject() [2/2]
DatabaseObject.DatabaseObject (SessionObject session, string replicationID, string server)
Database constructor method
Parameters
session
replicationID
server
Definition at line 183 of file DatabaseObject.cs.
                                                                                       {
        _Session = session;
        _ReplicationID = replicationID;
        _ServerName = server;
    }
Member Function Documentation
GetAllDocuments()
bool DatabaseObject.GetAllDocuments ()
Retrieve all documents from the database
Triggers an all documents request
All documents found will be added to the property 'Documents'
Returns
Boolean
Definition at line 404 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                  {
        Connector.ResetReturn();
        if (_isInitialized) {
            if (_Session.Connection.Request.ExecuteAllDocumentsRequest(_Session.
      WebServiceURL, null, null, null, null, this)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsAndFiles()
bool DatabaseObject.GetAllDocumentsAndFiles ()
Retrieve all documents from the database This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Triggers an all documents request
All documents found will be added to the property 'Documents'
Returns
Boolean
Definition at line 423 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            if (_Session.Connection.Request.ExecuteAllDocumentsFilesRequest(_Session.
      WebServiceURL, null, null, null, null, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsAndFilesByFormula()
bool DatabaseObject.GetAllDocumentsAndFilesByFormula (string formula)
Retrieve all documents from this database that correspond to the provided formula This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
formula
Returns
Boolean
Definition at line 467 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            if (_Session.Connection.Request.ExecuteAllDocumentsFilesRequest(_Session.
      WebServiceURL, null, null, formula, null, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsAndFilesByKey()
bool DatabaseObject.GetAllDocumentsAndFilesByKey (string searchField, string searchValue)
Retrieve all documents from this database by searching for a specific value in the provided field This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
searchField
searchValue
Returns
Boolean
Definition at line 608 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            if (_Session.Connection.Request.ExecuteAllDocumentsFilesRequest(_Session.
      WebServiceURL, searchField, searchValue, null, null, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsAndFilesByUnids() [1/2]
bool DatabaseObject.GetAllDocumentsAndFilesByUnids (string unids)
Retrieve all documents from this database by universalIDs This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Provide the universalIds separated by ;
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
unids
Returns
Boolean
Definition at line 513 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            if (_Session.Connection.Request.ExecuteAllDocumentsFilesRequest(_Session.
      WebServiceURL, null, null, null, unids, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsAndFilesByUnids() [2/2]
bool DatabaseObject.GetAllDocumentsAndFilesByUnids (IList listUnids)
Retrieve all documents from this database by universalIDs This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
listUnids
Returns
Boolean
Definition at line 559 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            string unids = Common.GetListAsString(listUnids, ";");
            if (_Session.Connection.Request.ExecuteAllDocumentsFilesRequest(_Session.
      WebServiceURL, null, null, null, unids, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsByFormula()
bool DatabaseObject.GetAllDocumentsByFormula (string formula)
Retrieve all documents from this database that correspond to the provided formula
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
formula
Returns
Boolean
Definition at line 447 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                         {
        Connector.ResetReturn();
        if (_isInitialized) {
            if (_Session.Connection.Request.ExecuteAllDocumentsRequest(_Session.
      WebServiceURL, null, null, formula, null, this)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsByKey()
bool DatabaseObject.GetAllDocumentsByKey (string searchField, string searchValue)
Retrieve all documents from this database by searching for a specific value in the provided field
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
searchField
searchValue
Returns
Boolean
Definition at line 586 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                                             {
        Connector.ResetReturn();
        if (_isInitialized) {
            if (_Session.Connection.Request.ExecuteAllDocumentsRequest(_Session.
      WebServiceURL,searchField,searchValue,null, null, this)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsByUnids() [1/2]
bool DatabaseObject.GetAllDocumentsByUnids (string unids)
Retrieve all documents from this database by universalIDs
Provide the universalIds separated by ;
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
unids
Returns
Boolean
Definition at line 492 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                     {
        Connector.ResetReturn();
        if (_isInitialized) {
            if (_Session.Connection.Request.ExecuteAllDocumentsRequest(_Session.
      WebServiceURL, null, null, null, unids, this)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
GetAllDocumentsByUnids() [2/2]
bool DatabaseObject.GetAllDocumentsByUnids (IList listUnids)
Retrieve all documents from this database by universalIDs
Triggers an all documents request
All documents found will be added to the property 'Documents'
Parameters
listUnids
Returns
Boolean
Definition at line 537 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                        {
        Connector.ResetReturn();
        if (_isInitialized) {
            string unids = Common.GetListAsString(listUnids, ";");
            if (_Session.Connection.Request.ExecuteAllDocumentsRequest(_Session.
      WebServiceURL, null, null, null, unids, this)) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
GetDocument()
DocumentObject DatabaseObject.GetDocument (string unid)
Retrieve a document from this database by universalID
Triggers a document request
The document will be added to the property 'Documents'
Parameters
unid
Returns
DocumentObject
Definition at line 255 of file DatabaseObject.cs.
References DocumentObject.Initialize().
                                                   {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized) {
            docObj = new DocumentObject(this, unid);
            if (docObj.Initialize()) {
                return docObj;
            } else {
                return null;
            }
        }
        return docObj;
    }
GetDocumentAndFiles()
DocumentObject DatabaseObject.GetDocumentAndFiles (string unid)
Retrieve a document from this database by universalID This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Triggers a document request
The document will be added to the property 'Documents'
Parameters
unid
Returns
DocumentObject
Definition at line 277 of file DatabaseObject.cs.
References DocumentObject.InitializeWithFiles().
    {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized)
        {
            docObj = new DocumentObject(this, unid);
            if (docObj.InitializeWithFiles())
            {
                return docObj;
            }
            else
            {
                return null;
            }
        }
        return docObj;
    }
GetDocumentAndFilesByFormula()
DocumentObject DatabaseObject.GetDocumentAndFilesByFormula (string formula)
Retrieve a document from this database by searching using the provided formula. This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
The first document found will be returned
Triggers a document request
The document will be added to the property 'Documents'
Parameters
formula
Returns
DocumentObject
Definition at line 379 of file DatabaseObject.cs.
References DocumentObject.InitializeWithFiles().
    {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized)
        {
            docObj = new DocumentObject(formula, this);
            if (docObj.InitializeWithFiles())
            {
                return docObj;
            }
            else
            {
                return null;
            }
        }
        return docObj;
    }
GetDocumentAndFilesByKey()
DocumentObject DatabaseObject.GetDocumentAndFilesByKey (string searchField, string searchValue)
Retrieve a document from this database by searching for a specific value in the provided field. This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
The first document found will be returned
Triggers a document request
The document will be added to the property 'Documents'
Parameters
searchField
searchValue
Returns
DocumentObject
Definition at line 329 of file DatabaseObject.cs.
References DocumentObject.InitializeWithFiles().
    {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized)
        {
            docObj = new DocumentObject(this, searchField, searchValue);
            if (docObj.InitializeWithFiles())
            {
                return docObj;
            }
            else
            {
                return null;
            }
        }
        return docObj;
    }
GetDocumentByFormula()
DocumentObject DatabaseObject.GetDocumentByFormula (string formula)
Retrieve a document from this database by searching using the provided formula.
The first document found will be returned
Triggers a document request
The document will be added to the property 'Documents'
Parameters
formula
Returns
DocumentObject
Definition at line 356 of file DatabaseObject.cs.
References DocumentObject.Initialize().
                                                               {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized) {
            docObj = new DocumentObject(formula,this);
            if (docObj.Initialize()) {
                return docObj;
            } else {
                return null;
            }
        }
        return docObj;
    }
GetDocumentByKey()
DocumentObject DatabaseObject.GetDocumentByKey (string searchField, string searchValue)
Retrieve a document from this database by searching for a specific value in the provided field.
The first document found will be returned
Triggers a document request
The document will be added to the property 'Documents'
Parameters
searchField
searchValue
Returns
DocumentObject
Definition at line 305 of file DatabaseObject.cs.
References DocumentObject.Initialize().
                                                                                   {
        Connector.ResetReturn();
        DocumentObject docObj = null;
        if (_isInitialized) {
            docObj = new DocumentObject(this, searchField,searchValue);
            if (docObj.Initialize()) {
                return docObj;
            } else {
                return null;
            }
        }
        return docObj;
    }
Initialize()
bool DatabaseObject.Initialize ()
Initializes the DatabaseObject by validating the input and triggering the database request
Returns
Boolean
Definition at line 197 of file DatabaseObject.cs.
References SessionObject.Connection, Connector.hasError, and SessionObject.WebServiceURL.
Referenced by SessionObject.GetDatabase(), and SessionObject.GetDatabaseByID().
                             {
        Connector.ResetReturn();
        // reset the list of docs
        _Documents = null;
        if (!ValidateInput()) {
            _isInitialized = false;
            Connector.hasError = true;
            return false; // throws exception
        }
        // make a connection to the webservice database - this will check the users authentication on that
       database
        if (_Session.Connection.Request.ExecuteDatabaseRequest(_Session.
      WebServiceURL, _ServerName, _FilePath, _ReplicationID, this)) {
            _isInitialized = true;
            Connector.hasError = false;
            return true;
        } else {
            //error messages written to Connection.ReturnMessages by
       Connection.Request.ExecuteSessionRequest
            _isInitialized = false;
            return false;
        }
                
    }
LoadDocumentFields() [1/2]
bool DatabaseObject.LoadDocumentFields (string listFields)
Retrieve fields for all documents in the property 'Documents'
Provide the fields separated by ;
This action will update the property collection Fields inside each document object
Parameters
listFields
Returns
Boolean
Definition at line 632 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                      {
        Connector.ResetReturn();
        if (_isInitialized && _Documents != null && _Documents.Count > 0) {
            if (_Session.Connection.Request.ExecuteAllFieldsRequest(_Session.
      WebServiceURL,this,listFields)) {
                return true;
            } else {
                return false;
            }
        }
        return true;
    }
LoadDocumentFields() [2/2]
bool DatabaseObject.LoadDocumentFields (IList listFields)
Retrieve fields for all documents in the property 'Documents'
This action will update the property collection Fields inside each document object
Parameters
listFields
Returns
Boolean
Definition at line 650 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
                                                     {
        Connector.ResetReturn();
        if (_isInitialized && _Documents != null && _Documents.Count > 0) {
            string fields = Common.GetListAsString(listFields, ";");
            if (_Session.Connection.Request.ExecuteAllFieldsRequest(_Session.
      WebServiceURL, this, fields)) {
                return true;
            } else {
                return false;
            }
        }
        return true;
    }
LoadDocumentFiles()
bool DatabaseObject.LoadDocumentFiles ()
Retrieve file objects for all documents in the property 'Documents'
This action will update the property collection Files inside each document object
Returns
Boolean
Definition at line 668 of file DatabaseObject.cs.
References SessionObject.Connection, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized && _Documents != null && _Documents.Count > 0)
        {
            if (_Session.Connection.Request.ExecuteAllFilesRequest(_Session.
      WebServiceURL, this))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return true;
    }
Property Documentation
Documents
Dictionary<string, DocumentObject> DatabaseObject.Documents [get], [set]
Collection of retrieved DocumentObjects stored in a dictionary with key universalID of the document
Definition at line 150 of file DatabaseObject.cs.
                                                        {
        get {
            return _Documents;
        }
        protected internal set {
            _Documents = value;
        }
    }
FilePath
string DatabaseObject.FilePath [get], [set]
Database FilePath
Definition at line 63 of file DatabaseObject.cs.
                           {
        get {
            return _FilePath;
        }
        protected internal set {
            _FilePath = value;
        }
    }
IsInitialized
bool DatabaseObject.IsInitialized [get]
Indicates is the DatabaseObject has been initialized
Definition at line 54 of file DatabaseObject.cs.
                              {
        get {
            return _isInitialized;
        }
    }
ReplicationID
string DatabaseObject.ReplicationID [get], [set]
Database ReplicationID
Definition at line 75 of file DatabaseObject.cs.
                                {
        get {
            return _ReplicationID;
        }
        protected internal set {
            _ReplicationID = value;
        }
    }
ServerName
string DatabaseObject.ServerName [get], [set]
Database ServerName
Definition at line 87 of file DatabaseObject.cs.
                             {
        get {
            return _ServerName;
        }
        protected internal set {
            _ServerName = value;
        }
    }
Session
SessionObject DatabaseObject.Session [get]
Reference to the session object that retrieve this database object
Definition at line 45 of file DatabaseObject.cs.
Referenced by FileObject.ExtractFile(), DocumentObject.GetAllFields(), DocumentObject.GetFields(), DocumentObject.GetFiles(), DocumentObject.Initialize(), and DocumentObject.InitializeWithFiles().
                                 {
        get {
            return _Session;
        }
    }
Size
string DatabaseObject.Size [get], [set]
Database size (bytes, Kb, Mb, Gb, Tb)
Definition at line 124 of file DatabaseObject.cs.
                       {
        get {
            return _Size;
        }
          protected internal set {
            _Size = value;
        }
    }
Template
string DatabaseObject.Template [get], [set]
Database Template name
Definition at line 111 of file DatabaseObject.cs.
                           {
        get {
            return _Template;
        }
        protected internal set {
            _Template = value;
        }
    }
Title
string DatabaseObject.Title [get], [set]
Database Title
Definition at line 99 of file DatabaseObject.cs.
                        {
        get {
            return _Title;
        }
        protected internal set {
            _Title = value;
        }
    }
Url
string DatabaseObject.Url [get], [set]
Database URL
Definition at line 137 of file DatabaseObject.cs.
                      {
        get {
            return _Url;
        }
        protected internal set {
            _Url = value;
        }
    }
The documentation for this class was generated from the following file:
C:/Users/Acketk/source/repos/VSTS/XPagesAPI/XPagesAPI/Objects/DatabaseObject.cs