DocumentObject Class Reference
An object representing a Domino Document
Public Member Functions
DocumentObject (DatabaseObject dbObj, String UniversalID)
DocumentObject Constructor
DocumentObject (DatabaseObject dbObj, string SeachField, string SearchValue)
DocumentObject Constructor
DocumentObject (string formula, DatabaseObject dbObj)
DocumentObject Constructor
bool Initialize ()
Initializes the document by validating the input and triggering the document request
bool InitializeWithFiles ()
Initializes the document by validating the input and triggering the document request This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
bool GetFields (string fields)
Retrieve fields for this documents by triggering the field request
bool GetFiles ()
Retrieve file objects for this documents by triggering the document files request
bool GetFields (IList fields)
Retrieve fields for this documents by triggering the field request
bool GetAllFields ()
Retrieve all fields for this documents by triggering the all fields request
bool ExportFields (string filePath, bool overwriteExistingFile)
Exports the content of the property 'Fields' to a file
bool ExportFiles (string filePath, bool overwriteExistingFile)
Exports the files from the XPages URL for all FileObjects in the Files property
Properties
DatabaseObject Database [get]
Reference to this documents database object
bool IsInitialized [get, set]
Indicates that the document isInitialized
string Size [get, set]
Document Size
string Url [get, set]
Document URL
string Form [get, set]
Documents Form (if any)
string NoteID [get, set]
Document NoteId
SortedDictionary< string, FieldObject > Fields [get, set]
Collection of retrieved FieldObjects stored in a dictionary with key name of the field
SortedDictionary< string, FileObject > Files [get, set]
Collection of retrieved FileObjects stored in a dictionary with key filename of the attachment
string UniversalID [get, set]
Document UniversalID
string DateCreated [get, set]
Document Creation Date
string DateModified [get, set]
Document Modification Date
Detailed Description
An object representing a Domino Document
The following is an example of the usage of a DocumentObject:
DocumentObject docObj = new DocumentObject(dbObj, universalID); // create new
       doc object by databaseobject and universalID
// DocumentObject docObj = new DocumentObject(dbObj, SeachField, SearchValue); // create new doc object by
       databaseobject and supplying a searchfield/value
// DocumentObject docObj = new DocumentObject(formula, dbObj); // create new doc object by databaseobject
       and supplying a formula
if(docObj!=null &amp;&amp; docObj.Initialize()){
     // here you can then get the fields of the document object
     // your code here...
}
Definition at line 24 of file DocumentObject.cs.
Constructor & Destructor Documentation
DocumentObject() [1/3]
DocumentObject.DocumentObject (DatabaseObject dbObj, String UniversalID)
DocumentObject Constructor
Parameters
dbObj
UniversalID
Definition at line 196 of file DocumentObject.cs.
References UniversalID.
    {
        _Database = dbObj;
        _UniversalID = UniversalID;
    }
DocumentObject() [2/3]
DocumentObject.DocumentObject (DatabaseObject dbObj, string SeachField, string SearchValue)
DocumentObject Constructor
Parameters
dbObj
SeachField
SearchValue
Definition at line 208 of file DocumentObject.cs.
    {
        _Database = dbObj;
        _SearchField = SeachField;
        _SearchValue = SearchValue;
    }
DocumentObject() [3/3]
DocumentObject.DocumentObject (string formula, DatabaseObject dbObj)
DocumentObject Constructor
Parameters
formula
dbObj
Definition at line 220 of file DocumentObject.cs.
    {
        _Database = dbObj;
        _Formula = formula;
    }
Member Function Documentation
ExportFields()
bool DocumentObject.ExportFields (string filePath, bool overwriteExistingFile)
Exports the content of the property 'Fields' to a file
Provide the path to the file and specify if you want to overwrite this file if it exists
Parameters
filePath
overwriteExistingFile
Returns
Definition at line 435 of file DocumentObject.cs.
References Fields, Connector.hasError, Connector.ReturnMessages, and UniversalID.
    {
        Connector.ResetReturn();
        try
        {
            if (Fields != null && Fields.Count > 0)
            {
                //write all to stringbuilder, output to file
                StringBuilder sb = new StringBuilder();
                foreach (KeyValuePair<string, FieldObject> field in Fields)
                {
                    if (field.Value.Type.Equals("[FIELDNOTFOUND]"))
                    {
                        sb.AppendLine(field.Value.Name + " : " + field.Value.Type); // add type to indicate
       the field was not found
                    }
                    else
                    {
                        sb.AppendLine(field.Value.Name + " : " + field.Value.GetValueAsString()); //+ " ("
       + field.Value.Type + ")");
                    }
                }
                if (File.Exists(filePath))
                {
                    if (overwriteExistingFile)
                    {
                        File.Delete(filePath);
                    }
                    else
                    {
                        Connector.ReturnMessages.Add("Unable to export the fields to
       the file : " + filePath);
                        Connector.ReturnMessages.Add("A file already exist with the
       same name, provide a new file path");
                        // Connector.hasError = true;
                        return false;
                    }
                }
                //File.CreateText(filePath);
                File.WriteAllText(filePath, sb.ToString());
                Connector.ReturnMessages.Add("Exported all fields of document : " +
      UniversalID + " to the file : " + filePath);
                return true;
            }
            else
            {
                Connector.ReturnMessages.Add("The document : " +
      UniversalID + " does not contain any fields to export");
                return false;
            }
        }
        catch (Exception ex)
        {
            Connector.ReturnMessages.Add("Unable to export the fields to the file :
      " + filePath);
            Connector.ReturnMessages.Add(Common.GetErrorInfo(ex));
            Connector.hasError = true;
            return false;
        }
    }
ExportFiles()
bool DocumentObject.ExportFiles (string filePath, bool overwriteExistingFile)
Exports the files from the XPages URL for all FileObjects in the Files property
Provide the path to the file and specify if you want to overwrite this file if it exists
Parameters
filePath
overwriteExistingFile
Returns
Definition at line 497 of file DocumentObject.cs.
References FileObject.ExtractFile(), Files, Connector.hasError, FileObject.Name, Connector.ReturnMessages, and UniversalID.
    {
        Connector.ResetReturn();
        try
        {
            if (Files != null && Files.Count > 0)
            {
              
                if (!Directory.Exists(filePath))
                {
                    //create folde structure
                    Directory.CreateDirectory(filePath);
                }
                
                foreach(FileObject fObj in Files.Values)
                {
                    string fileName = "";
                    fileName = System.IO.Path.Combine(filePath,fObj.Name);
                    if (File.Exists(fileName))
                    {
                        if (overwriteExistingFile) {
                            File.Delete(fileName);
                        }
                        else
                        {
                            Connector.ReturnMessages.Add("Unable to export the file
       to : " + filePath);
                            Connector.ReturnMessages.Add("A file already exist with
       the same name, provide a new file path");
                            // Connector.hasError = true;
                            return false;
                        }
                      
                    }
                    if (!fObj.ExtractFile(fileName))
                    {
                        Connector.ReturnMessages.Insert(0,"Unable to export the file
       : " + fObj.Name);
                        Connector.hasError = true;
                        return false;
                    }
                    
                }
             
                Connector.ReturnMessages.Add("Exported all fields of document : " +
      UniversalID + " to the file : " + filePath);
                return true;
            }
            else
            {
                Connector.ReturnMessages.Add("The document : " +
      UniversalID + " does not contain any fields to export");
                return false;
            }
        }
        catch (Exception ex)
        {
            Connector.ReturnMessages.Add("Unable to export the fields to the file :
      " + filePath);
            Connector.ReturnMessages.Add(Common.GetErrorInfo(ex));
            Connector.hasError = true;
            return false;
        }
    }
GetAllFields()
bool DocumentObject.GetAllFields ()
Retrieve all fields for this documents by triggering the all fields request
This action will update the property 'Fields'
Returns
Boolean
Definition at line 409 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
    {
        //get all the fields from the domino document and store them in Fields
        Connector.ResetReturn();
        if (_isInitialized)
        {
            if (_Database.Session.Connection.Request.ExecuteFieldsRequest(_Database.
      Session.WebServiceURL, this, null))
            {
                Connector.hasError = false;
                return true;
            }
        }
        return false;
    }
GetFields() [1/2]
bool DocumentObject.GetFields (string fields)
Retrieve fields for this documents by triggering the field request
Provide the fields separated by ;
This action will update the property 'Fields'
Parameters
fields
Returns
Boolean
Definition at line 331 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        if (_isInitialized)
        {
            // if (!String.IsNullOrEmpty(fields)) {
            //this will update _Fields list in this object
            if (_Database.Session.Connection.Request.ExecuteFieldsRequest(_Database.
      Session.WebServiceURL, this, fields))
            {
                Connector.hasError = false;
                return true;
            }
            //}
        }
        return false;
        // get the fields from XPages
    }
GetFields() [2/2]
bool DocumentObject.GetFields (IList fields)
Retrieve fields for this documents by triggering the field request
This action will update the property 'Fields'
Parameters
fields
Returns
Boolean
Definition at line 381 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        string f = "";
        if (_isInitialized)
        {
            f = Common.GetListAsString(fields, ";"); // can be empty - get's all fields
            // if (!String.IsNullOrEmpty(fields)) {
            //this will update _Fields list in this object
            if (_Database.Session.Connection.Request.ExecuteFieldsRequest(_Database.
      Session.WebServiceURL, this, f))
            {
                Connector.hasError = false;
                return true;
            }
            //}
        }
        return false;
    }
GetFiles()
bool DocumentObject.GetFiles ()
Retrieve file objects for this documents by triggering the document files request
This action will update the property 'Files'
Returns
Boolean
Definition at line 356 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
    {
        Connector.ResetReturn();
        // get the files from XPages
        if (_isInitialized)
        {
            //this will update _Fields list in this object
            //string WebServiceURL, string Unid, string searchField, string searchValue, string formula,
       DatabaseObject dbObj, DocumentObject docObj
            if (_Database.Session.Connection.Request.ExecuteDocumentFilesRequest(_Database
      .Session.WebServiceURL, this._UniversalID,this._SearchField,this._SearchValue, this.
      _Formula,this._Database, this))
            {
                Connector.hasError = false;
                return true;
            }
        }
        return false;
    }
Initialize()
bool DocumentObject.Initialize ()
Initializes the document by validating the input and triggering the document request
Returns
Boolean
Definition at line 263 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
Referenced by DatabaseObject.GetDocument(), DatabaseObject.GetDocumentByFormula(), and DatabaseObject.GetDocumentByKey().
    {
        Connector.ResetReturn();
        if (!ValidateInput())
        {
            _isInitialized = false;
            Connector.hasError = true;
            return false; // throws exception
        }
        // make a connection to the webservice database - this will check the users authentication on that
       database
        if (_Database.Session.Connection.Request.ExecuteDocumentRequest(_Database.
      Session.WebServiceURL, _UniversalID, _SearchField, _SearchValue, _Formula, _Database,
      this))
        {
            _isInitialized = true;
            // Connector.ReturnMessages.Add("Document Initialized : " + _UniversalID + " in : " +
       _Database.FilePath + " from : "+_Database.ServerName + " (DocumentObject.Initialize)");
            Connector.hasError = false;
            return true;
        }
        else
        {
            //error messages written to Connection.ReturnMessages by
       Connection.Request.ExecuteSessionRequest
            _isInitialized = false;
            return false;
        }
    }
InitializeWithFiles()
bool DocumentObject.InitializeWithFiles ()
Initializes the document by validating the input and triggering the document request This function will, in addition to retrieving the default document information, retrieve the associated domino attachment file objects
Returns
Boolean
Definition at line 296 of file DocumentObject.cs.
References SessionObject.Connection, Connector.hasError, DatabaseObject.Session, and SessionObject.WebServiceURL.
Referenced by DatabaseObject.GetDocumentAndFiles(), DatabaseObject.GetDocumentAndFilesByFormula(), and DatabaseObject.GetDocumentAndFilesByKey().
    {
        Connector.ResetReturn();
        if (!ValidateInput())
        {
            _isInitialized = false;
            Connector.hasError = true;
            return false; // throws exception
        }
        // make a connection to the webservice database - this will check the users authentication on that
       database
        if (_Database.Session.Connection.Request.ExecuteDocumentFilesRequest(_Database.
      Session.WebServiceURL, _UniversalID, _SearchField, _SearchValue, _Formula, _Database,
      this))
        {
            _isInitialized = true;
            // Connector.ReturnMessages.Add("Document Initialized : " + _UniversalID + " in : " +
       _Database.FilePath + " from : "+_Database.ServerName + " (DocumentObject.Initialize)");
            Connector.hasError = false;
            return true;
        }
        else
        {
            //error messages written to Connection.ReturnMessages by
       Connection.Request.ExecuteSessionRequest
            _isInitialized = false;
            return false;
        }
    }
Property Documentation
Database
DatabaseObject DocumentObject.Database [get]
Reference to this documents database object
Definition at line 52 of file DocumentObject.cs.
Referenced by FileObject.ExtractFile().
                                   {
        get {
            return _Database;
        }
    }
DateCreated
string DocumentObject.DateCreated [get], [set]
Document Creation Date
Definition at line 164 of file DocumentObject.cs.
                              {
        get {
            return _DateCreated;
        }
        set {
            _DateCreated = value;
        }
    }
DateModified
string DocumentObject.DateModified [get], [set]
Document Modification Date
Definition at line 177 of file DocumentObject.cs.
                               {
        get {
            return _DateModified;
        }
        set {
            _DateModified = value;
        }
    }
Fields
SortedDictionary<string, FieldObject> DocumentObject.Fields [get], [set]
Collection of retrieved FieldObjects stored in a dictionary with key name of the field
Definition at line 125 of file DocumentObject.cs.
Referenced by ExportFields().
                                                        {
        get {
            return _Fields;
        }
        protected internal set {
            _Fields = value;
        }
    }
Files
SortedDictionary<string, FileObject> DocumentObject.Files [get], [set]
Collection of retrieved FileObjects stored in a dictionary with key filename of the attachment
Definition at line 138 of file DocumentObject.cs.
Referenced by ExportFiles().
                                                      {
        get {
            return _Files;
        }
        protected internal set {
            _Files = value;
        }
    }
Form
string DocumentObject.Form [get], [set]
Documents Form (if any)
Definition at line 99 of file DocumentObject.cs.
                       {
        get {
            return _Form;
        }
        protected internal set {
            _Form = value;
        }
    }
IsInitialized
bool DocumentObject.IsInitialized [get], [set]
Indicates that the document isInitialized
Definition at line 61 of file DocumentObject.cs.
                              {
        get {
            return _isInitialized;
        }
        protected internal set {
            _isInitialized = value;
        }
    }
NoteID
string DocumentObject.NoteID [get], [set]
Document NoteId
Definition at line 112 of file DocumentObject.cs.
                         {
        get {
            return _NoteID;
        }
        protected internal set {
            _NoteID = value;
        }
    }
Size
string DocumentObject.Size [get], [set]
Document Size
Definition at line 73 of file DocumentObject.cs.
                       {
        get {
            return _Size;
        }
        protected internal set {
            _Size = value;
        }
    }
UniversalID
string DocumentObject.UniversalID [get], [set]
Document UniversalID
Definition at line 151 of file DocumentObject.cs.
Referenced by DocumentObject(), ExportFields(), and ExportFiles().
                              {
        get {
            return _UniversalID;
        }
        protected internal set {
            _UniversalID = value;
        }
    }
Url
string DocumentObject.Url [get], [set]
Document URL
Definition at line 86 of file DocumentObject.cs.
                      {
        get {
            return _Url;
        }
        protected internal set {
            _Url = value;
        }
    }
The documentation for this class was generated from the following file:
C:/Users/Acketk/source/repos/VSTS/XPagesAPI/XPagesAPI/Objects/DocumentObject.cs